# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiaColsToPlot(object):
    def setupUi(self, DiaColsToPlot):
        DiaColsToPlot.setObjectName("DiaColsToPlot")
        DiaColsToPlot.resize(213, 210)
        DiaColsToPlot.setSizeGripEnabled(False)
        DiaColsToPlot.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(DiaColsToPlot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DiaColsToPlot)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.list_dialog = QtWidgets.QListWidget(DiaColsToPlot)
        self.list_dialog.setAutoFillBackground(True)
        self.list_dialog.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.list_dialog.setFrameShadow(QtWidgets.QFrame.Plain)
        self.list_dialog.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_dialog.setProperty("showDropIndicator", False)
        self.list_dialog.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.list_dialog.setAlternatingRowColors(True)
        self.list_dialog.setObjectName("list_dialog")
        self.horizontalLayout_2.addWidget(self.list_dialog)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(DiaColsToPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DiaColsToPlot)
        self.buttonBox.accepted.connect(DiaColsToPlot.close)
        self.buttonBox.rejected.connect(DiaColsToPlot.close)
        self.buttonBox.accepted.connect(DiaColsToPlot.accept)
        QtCore.QMetaObject.connectSlotsByName(DiaColsToPlot)

    def retranslateUi(self, DiaColsToPlot):
        _translate = QtCore.QCoreApplication.translate
        DiaColsToPlot.setWindowTitle(_translate("DiaColsToPlot", "Plotelemente"))
        self.label.setText(_translate("DiaColsToPlot", "Welche Spalten sollen geplottet werden?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DiaColsToPlot = QtWidgets.QDialog()
    ui = Ui_DiaColsToPlot()
    ui.setupUi(DiaColsToPlot)
    DiaColsToPlot.show()
    sys.exit(app.exec_())
