# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plotting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWindow(object):
    def setupUi(self, PlotWindow):
        PlotWindow.setObjectName("PlotWindow")
        PlotWindow.resize(481, 472)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(PlotWindow)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_element = QtWidgets.QComboBox(PlotWindow)
        self.cb_element.setObjectName("cb_element")
        self.horizontalLayout.addWidget(self.cb_element)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cb_toggle_smooth = QtWidgets.QCheckBox(PlotWindow)
        self.cb_toggle_smooth.setObjectName("cb_toggle_smooth")
        self.horizontalLayout.addWidget(self.cb_toggle_smooth)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.graphWidget = PlotWidget(PlotWindow)
        self.graphWidget.setObjectName("graphWidget")
        self.verticalLayout.addWidget(self.graphWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labSlider = QtWidgets.QLabel(PlotWindow)
        self.labSlider.setEnabled(False)
        self.labSlider.setObjectName("labSlider")
        self.horizontalLayout_2.addWidget(self.labSlider)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(PlotWindow)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.slider = QtWidgets.QSlider(PlotWindow)
        self.slider.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider.sizePolicy().hasHeightForWidth())
        self.slider.setSizePolicy(sizePolicy)
        self.slider.setMinimumSize(QtCore.QSize(200, 0))
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout_2.addWidget(self.slider)
        self.txt_max = QtWidgets.QLineEdit(PlotWindow)
        self.txt_max.setEnabled(False)
        self.txt_max.setMaximumSize(QtCore.QSize(35, 16777215))
        self.txt_max.setObjectName("txt_max")
        self.horizontalLayout_2.addWidget(self.txt_max)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(PlotWindow)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.labelCurrentValueSlider = QtWidgets.QLabel(PlotWindow)
        self.labelCurrentValueSlider.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCurrentValueSlider.sizePolicy().hasHeightForWidth())
        self.labelCurrentValueSlider.setSizePolicy(sizePolicy)
        self.labelCurrentValueSlider.setMinimumSize(QtCore.QSize(24, 0))
        self.labelCurrentValueSlider.setMaximumSize(QtCore.QSize(24, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelCurrentValueSlider.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCurrentValueSlider.setFont(font)
        self.labelCurrentValueSlider.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelCurrentValueSlider.setTextFormat(QtCore.Qt.RichText)
        self.labelCurrentValueSlider.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCurrentValueSlider.setObjectName("labelCurrentValueSlider")
        self.horizontalLayout_2.addWidget(self.labelCurrentValueSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PlotWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotWindow)

    def retranslateUi(self, PlotWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWindow.setWindowTitle(_translate("PlotWindow", "Plotfenster"))
        self.label.setText(_translate("PlotWindow", "Element"))
        self.cb_element.setToolTip(_translate("PlotWindow", "Element, welches geplotted werden soll."))
        self.cb_toggle_smooth.setToolTip(_translate("PlotWindow", "Hier kann die globale Einstellung des Glättens überschrieben werden (sinnvoll zum testen)"))
        self.cb_toggle_smooth.setText(_translate("PlotWindow", "Glätten"))
        self.labSlider.setText(_translate("PlotWindow", "Glättungsparameter"))
        self.label_3.setText(_translate("PlotWindow", "1"))
        self.txt_max.setToolTip(_translate("PlotWindow", "Maximalwert des Sliders. Verringern für präzisere Einstellung."))
        self.label_2.setText(_translate("PlotWindow", "Akt:"))
        self.labelCurrentValueSlider.setText(_translate("PlotWindow", "0"))
from pyqtgraph import PlotWidget
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotWindow = QtWidgets.QDialog()
    ui = Ui_PlotWindow()
    ui.setupUi(PlotWindow)
    PlotWindow.show()
    sys.exit(app.exec_())
